// Auto-generated by scripts/generate-sdk-docs.mjs — do not edit manually
export const sdkMeta = {
  "auth0-fastapi-api": {
    "label": "auth0-fastapi-api",
    "icon": null,
    "versions": [
      {
        "version": "v1",
        "status": "active",
        "landingPage": "auth0-fastapi"
      }
    ]
  },
  "auth0-go": {
    "label": "Go",
    "icon": "golang",
    "versions": [
      {
        "version": "v5",
        "status": "active",
        "landingPage": "new"
      }
    ]
  },
  "auth0-java-mvc-common": {
    "label": "auth0-java-mvc-common",
    "icon": null,
    "versions": [
      {
        "version": "v1",
        "status": "active",
        "landingPage": "authentication-controller"
      }
    ]
  },
  "auth0-python": {
    "label": "Python",
    "icon": "python",
    "versions": [
      {
        "version": "v4",
        "status": "active",
        "landingPage": "authentication"
      }
    ]
  },
  "auth0-react": {
    "label": "React",
    "icon": "react",
    "versions": [
      {
        "version": "v2",
        "status": "active",
        "landingPage": "auth0provider"
      }
    ]
  },
  "nextjs-auth0": {
    "label": "Next.js",
    "icon": "nextjs",
    "versions": [
      {
        "version": "v4",
        "status": "active",
        "landingPage": "auth0client"
      },
      {
        "version": "v3",
        "status": "deprecated",
        "landingPage": "init-auth0"
      }
    ]
  }
};
